version: '2.4'
services:
  prometheus_client:
    build:
      context: .
    image: prometheus_client:v0.0.0
    environment:
    - CLUSTER_NAME=cloud.internationalbrainlab.org
    volumes:
      - ./config:/config
    ports:
      - "9090:9090" #prometheus server
